### PR TITLE
Change documentation theme.

### PR DESCRIPTION
**Pull request by amageh**
As already discussed, we would like to implement a more attractive theme for our website and decided on [this](https://sphinx-themes.org/html/yummy-sphinx-theme/yummy_sphinx_theme/index.html) for now.

### CODE REVIEW

**Comment by hmgaudecker** [comment]
Thanks, looks great already!!! I also played around a bit with https://pypi.org/project/sphinx-material/, but that seems harder to turn into something workable and nice-looking.

Just a couple of things on my wishlist:

- Do we need the lightbulb in the header?
- Can we change the background colour of the header? When you scroll down, the white on white does not look so pretty...
- The big marks for the html anchors in the titles are ugly. Is it possible to remove them / make them white?

image

**Comment by amageh** [comment]
I made some additional changes to background and colors, still working on finding out how to change some things in the .css files (i.e. why links are currently orange, we can still change this). The goal is to get the website on brand with the nice [color scheme](https://github.com/covid-19-impact-lab/utilities/blob/dashboard/utilities/colors.py) we now have :-). 

Regarding your questions @hmgaudecker : 
1. Yes, we can change it to any (free) icon from the [fontawesome](https://fontawesome.com/icons?from=io) icon library. I changed it to a more neutral arrow now. I did not figure out how to completely remove it yet but I can work on that if you feel strongly about it.
2. I have thought this as well when scrolling down on the longer pages but I think changing it to a color will probably make it clash with the banner/color scheme on top. I'll try changing it and see how it looks. 
3. I totally agree,  removed the anchors!

**Comment by janosg** [comment]
Looks quite nice already!

**Comment by hmgaudecker** [comment]
Maybe one of these guys? https://fontawesome.com/icons?d=gallery&q=virus&m=free

**Comment by hmgaudecker** [comment]
Looks good to me, will go ahead and merge, we can always adjust later on!

**Pull request merged**
