### PR TITLE
Improvements to Website

### PR DESCRIPTION
**Pull request by amageh**
I am using this pull request to implement the valuable feedback given by Lars and Holger from IZA and other potential improvements to the website. I think I have added most of their suggestions. 

@hmgaudecker @janosg @roecla It would be great if you could have a look and comment on any other changes you would like (i.e. should I try to adjust the style/colors of the website to the IZA version?).

This version of the site is available as the Version `changes-website` [here](https://covid-19-impact-lab.readthedocs.io/en/changes-website/).

### CODE REVIEW

**Comment by hmgaudecker** [comment]
Great, will have a look asap!!!

@tobiasraabe, would you mind setting up the automatic rtd builds for PRs? Too easy to take that feature for granted...

**Comment by hmgaudecker** [comment]
> This version of the site is available as the Version `changes-website` [here](https://covid-19-impact-lab.readthedocs.io/en/changes-website/).

Seeing that only now (blush).

**Comment by hmgaudecker** [comment]
* Minor, since we will only ever have one live branch: No way to get to the index site of the branch; if I click on the link at the top, it redirects towards "en/latest"
* Intro paragraph:
  * To give meaningful answers to these questions it is -> No question posed... Reformulate the prior sentence a bit?
  * If initiatives beyond LISS (twitter?) are not p**d off, I would just be more concrete in our goals. We are running surveys doing near-real time monitoring of consequences, behaviour, ...
  * Our first survey -> our first paper; or explain that there will be much more to come.
* For the translation help, why not link directly to the blob?

Really, really cool!

**Comment by tobiasraabe** [comment]
I wrote an email to the rtd support. Should be available tomorrow.

**Comment by tobiasraabe** [comment]
They already enabled the feature.

**Comment by hmgaudecker** [comment]
@amageh: I would suggest fixing the minor things I noted and merge -- so much better than the current version and we can always improve. Thanks!

**Comment by amageh** [comment]
@hmgaudecker  Okay, I made some minor adjustments. Feel free to edit the text if you want or create issues if anything else comes up!

**Pull request merged**
