### PR TITLE
Add an about us page.

### PR DESCRIPTION
**Pull request by hmgaudecker**
I started with the things where I still might have an overview. Could somebody please take it from there?

@amageh @raholler @roecla @ChristianZimpelmann @janosg ?

### CODE REVIEW

**Comment by raholler** [comment]
Looks fine to me.. but I think some of the master students are missing...

**Comment by hmgaudecker** [comment]
Well, the entire data team is missing...

**Comment by janosg** [comment]
Looks good!

**Comment by hmgaudecker** [comment]
Are all of you pulling jokes on the old guy who does not give things a close enough look on other occasions?

**Comment by hmgaudecker** [comment]
So, seriously, could somebody please enumerate the data management an webscraping teams?

**Comment by janosg** [comment]
Added some more names but I have no idea if the data preparation stuff is complete. @ChristianZimpelmann, can you check?

Also: I think Annica deserves much more credit for her great job as community manager

**Comment by hmgaudecker** [comment]
> Also: I think Annica deserves much more credit for her great job as community manager

Indeed. How could I forget about that??? Thanks for noting!

Would be great if we had this out by Thursday lunchtime and nobody felt excluded!

**Pull request merged**
